---
title: "Week 5"
subtitle: "Data wrangling"
description: |
  Strings and factors
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r, include=FALSE}
  library(emo)
```

# Feb 14: Strings

## Prepare

* `r emo::ji("down_arrow")`: [String manipulation cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/strings.pdf)
* `r emo::ji("open_book")`: [R4DS Chapter 14](https://r4ds.had.co.nz/strings.html)
  
## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/wrangling5/wrangling5_deck.html) / Materials ([zip](https://www.dropbox.com/s/j3xm7iivf4u2glm/wrangling5.zip?dl=1))

## After Class (Optional)

`r emo::ji("tv")`: [Help me help you. Creating reproducible examples](https://www.rstudio.com/resources/webinars/help-me-help-you-creating-reproducible-examples/)

# Feb 16: Factors

## Prepare

* `r emo::ji("down_arrow")`: [Factors cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/factors.pdf)
* `r emo::ji("open_book")`: [R4DS Chapter 15](https://r4ds.had.co.nz/factors.html)

## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/wrangling6/wrangling6_deck.html) / Materials ([zip](https://www.dropbox.com/s/fr8ret9ms0xmu9p/wrangling6.zip?dl=1))

## After Class (Optional)

`r emo::ji("tv")`: [Tidyverse visualization manipulation basics](https://www.rstudio.com/resources/webinars/tidyverse-visualization-manipulation-basics/)

## TidyTuesday

You have two options this week: (1) TT Week 7 (2023); or (2) BYOD. Please pick one.

### Hollywood Age Gaps! (TT Week 7, 2023)

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/R4DScommunity?ref_src=twsrc%5Etfw">@R4DSCommunity</a> welcomes you to week 7 of <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a>! We&#39;re exploring Hollywood Age Gaps!<br><br>📁 <a href="https://t.co/IpzLp8RrNp">https://t.co/IpzLp8RrNp</a><br>🗞️ <a href="https://t.co/s1i9LSsm5I">https://t.co/s1i9LSsm5I</a><a href="https://twitter.com/hashtag/r4ds?src=hash&amp;ref_src=twsrc%5Etfw">#r4ds</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a> <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/DataViz?src=hash&amp;ref_src=twsrc%5Etfw">#DataViz</a> <a href="https://t.co/scgVHCCEin">pic.twitter.com/scgVHCCEin</a></p>&mdash; Jon Harmon (he/him) (@JonTheGeek) <a href="https://twitter.com/JonTheGeek/status/1625149069302841345?ref_src=twsrc%5Etfw">February 13, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

[Data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-02-14/readme.md) / [Template](https://www.dropbox.com/s/i1mf75oja07985u/tidytuesday.zip?dl=1)

### BYOD

You can bring your own data for the first part of the assignment (exploration), but please find a community example from TT Week 7 for the second part.
