---
title: "Week 2"
subtitle: "Data visualization"
description: |
  Plot layout and get to know a geom
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r, include=FALSE}
  library(emo)
```

# Jan 24: Common geoms and plot styles to know

## Prepare

* `r emo::ji("computer")`: Get to know a `geom`
  * Search Twitter again for more `#TidyTuesday` Week 3 (art history) entries
  * Find examples of at least 3 different geoms used in `#TidyTuesday` charts and write down the names of these geoms
  * Go to the {`ggplot2`} [reference documents](https://ggplot2.tidyverse.org/reference/#section-geoms) and find your selected geoms
  * For each geom you selected, run a few of the examples and see what happens when you modify the arguments
* `r emo::ji("computer")`: [Interactive {`ggplot2`} tutorial](https://learn.themethodsection.com/tutorials/ggplot2/basics/) from Ariel Muldoon (you'll run the code in the browser)
  
  
## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/dataviz3/dataviz3_deck.html) / Materials ([zip](https://www.dropbox.com/s/r3kkoveagn024a2/dataviz3.zip?dl=1))

## After Class (Optional)

* `r emo::ji("tv")`: [Effective visualizations](https://www.rstudio.com/resources/rstudioconf-2020/effective-visualizations/)
* `r emo::ji("tv")`: [The glamour of graphics](https://www.rstudio.com/resources/rstudioconf-2020/the-glamour-of-graphics/)

# Jan 26: Small multiples and patchwork

## Prepare

* `r emo::ji("open_book")`: [SOCVIZ Chapter 4 (4.1-4.4)](https://socviz.co/groupfacettx.html)
* `r emo::ji("open_book")`: [Review R4DS 3.5 on facets](https://r4ds.had.co.nz/data-visualisation.html#facets)
* `r emo::ji("open_book")`: [Blog post on comparing distributions](https://kieranhealy.org/blog/archives/2021/12/19/comparing-distributions/)
* `r emo::ji("tv")`: [Learning to use the patchwork R package (how to learn a package in general)](https://www.youtube.com/watch?v=2o1YDUKyhu0) ({[`patchwork`](https://patchwork.data-imaginist.com/articles/patchwork.html)})

## During Class

[Deck](https://ericpgreen.github.io/glhlth562/materials/dataviz4/dataviz4_deck.html) / Materials ([zip](https://www.dropbox.com/s/63sg2t4w472zswy/dataviz4.zip?dl=1))

## After Class (Optional)

* `r emo::ji("tv")`: [The little package that could: Taking visualizations to the next level with the scales package](https://www.rstudio.com/resources/rstudioconf-2020/the-little-package-that-could-taking-visualizations-to-the-next-level-with-the-scales-package/)
* `r emo::ji("tv")`: [Spruce up your ggplot2 visualizations with formatted text](https://www.rstudio.com/resources/rstudioconf-2020/spruce-up-your-ggplot2-visualizations-with-formatted-text/)



## TidyTuesday

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/R4DScommunity?ref_src=twsrc%5Etfw">@R4DSCommunity</a> welcomes you to week 4 of <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a>! We&#39;re exploring Alone data!<br><br>📁 <a href="https://t.co/ga8bVRHyz5">https://t.co/ga8bVRHyz5</a><br>🗞️ <a href="https://t.co/hfayPMJCri">https://t.co/hfayPMJCri</a><a href="https://twitter.com/hashtag/r4ds?src=hash&amp;ref_src=twsrc%5Etfw">#r4ds</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a> <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/DataViz?src=hash&amp;ref_src=twsrc%5Etfw">#DataViz</a> <a href="https://t.co/1p1gV6nWFQ">pic.twitter.com/1p1gV6nWFQ</a></p>&mdash; Jon Harmon (he/him) (@JonTheGeek) <a href="https://twitter.com/JonTheGeek/status/1617538796832137217?ref_src=twsrc%5Etfw">January 23, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Alone! [Data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-01-24/readme.md) / [Template](https://www.dropbox.com/s/i1mf75oja07985u/tidytuesday.zip?dl=1)

<iframe width="560" height="315" src="https://www.youtube.com/embed/iIb5OUgzL4k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
