---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(palmerpenguins)
library(tidyverse)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
sliderInput("alpha_level", label = "Alpha:",
            min = 0, max = 1, step = 0.2, value = 1)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlot({
  ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
    geom_boxplot(aes(color = species), width = 0.3, show.legend = FALSE) +
    geom_jitter(aes(color = species), alpha = input$alpha_level, 
                show.legend = FALSE, 
                position = position_jitter(width = 0.2, seed = 0)) +
    scale_color_manual(values = c("darkorange","purple","cyan4")) +
    theme_minimal() +
    labs(x = "Species",
         y = "Flipper length (mm)")
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

