---
title: "Old Faithful Eruptions"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
data(faithful)
library(palmerpenguins)
library(tidyverse)
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)

sliderInput("alpha_level", label = "Alpha:",
            min = 0, max = 1, step = 0.2, value = 1)
```

Column
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}
renderPlot({
  
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser Eruption Duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
  
})
```

Column
-----------------------------------------------------------------------

### Penguins

```{r}
renderPlot({
  
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
    geom_boxplot(aes(color = species), width = 0.3, show.legend = FALSE) +
    
    geom_jitter(aes(color = species), 
                #alpha = 0.5, 
                alpha = input$alpha_level,
                show.legend = FALSE, 
                position = position_jitter(width = 0.2, seed = 0)) +
    
    scale_color_manual(values = c("darkorange","purple","cyan4")) +
    theme_minimal() +
    labs(x = "Species",
         y = "Flipper length (mm)")
  
})
```

