---
title: "dplyr"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(feb2)
```

Objective: Calculate the percentage of yearly predictions that are "Early Spring"

```{r perEarlySpring}
# missing yearly entries
# year and/or decade
# limit to years with >= 5 predictions

earlySpring <- predictions %>%
# remove missing predictions for prognosticators
  filter(!is.na(prediction)) %>%
# count number of each type of prediction by year
  group_by(year, prediction) %>%
  count() %>%
  ungroup() %>%
# # check to see if any years only have 1 prediction type
#   group_by(year) %>%
#   count(name = "pred_type_year") %>%
#   filter(pred_type_year == 1) %>%
# 1983 and 1990 only have 1 type of prediction, so we want to add an explict 0
# complete is awesome; it adds rows so the dataset has complete combos of
#. year and prediction (so every year has both prediction types)
#. when adding a missing combination, n is set to be 0
  complete(year, prediction, fill=list(n = 0)) %>%
# sum the predictions made by year
  group_by(year) %>%
  mutate(denom = sum(n)) %>%
  ungroup() %>%
# calculate percentage (all info present per row so do not need grouping)
  mutate(per = n/denom) %>%
# drop years with fewer than 5 predictions
  filter(denom >= 5) %>%
# keep just Early Spring
  filter(prediction == "Early Spring")

# plot percentage
  earlySpring %>%
    ggplot(aes(x=year, y=per)) +
      geom_line() +
      labs(x=NULL, y=NULL,
           title = "Early Spring predictions appear to be on the decline",
           subtitle = "Percentage of Early Spring yearly predictions (limited to years with at least 5 predictions)",
           caption = str_wrap("Source: Countdown to Groundhog Day and U.S. National Ocean and Atmospheric Administration.", 100)) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_minimal() + 
    theme(plot.title.position = "plot",
          plot.title = element_text(face="bold"))
  
# plot numerator and denominator
  earlySpring %>%
  # first we need to make it longer (we'll learn this soon)
    select(-per, -prediction) %>%
    pivot_longer(cols = c(n, denom),
                 names_to = "variable",
                 values_to = "value") %>%
  # give nicer names to variables
    mutate(variable = case_when(
      variable == "denom" ~ "Total Predictions",
      TRUE ~ "Early Spring"
    )) %>%
  # add label for end of lines
    mutate(label = if_else(year == max(year), variable, NA_character_)) %>%
  # plot
    ggplot(aes(x=year, y=value, color = variable)) +
      geom_step() +
      labs(x=NULL, y=NULL,
           title = str_wrap("Predictions for an early spring decline as a share of the total as more prognosticators join in the Groundhog Day fun", 80),
           subtitle = "Count of Early Spring predictions and total yearly predictions\n(limited to years with at least 5 predictions)",
           caption = str_wrap("Source: Countdown to Groundhog Day and U.S. National Ocean and Atmospheric Administration.", 100)) +
    scale_color_manual(values = c("violet", "black")) + 
    geom_text(aes(label = label),
              nudge_x = 1, na.rm = TRUE, hjust = 0) + 
  # allow the labels to go off the plot
    coord_cartesian(clip = 'off') +
    theme_minimal() + 
    theme(plot.title.position = "plot",
          plot.title = element_text(face="bold"),
          legend.position = "none",
          # give more room for labels
          plot.margin = margin(0.1, 3, 0.1, 0.1, "cm")) # t-r-b-l
```



```{r}
predictions %>%
# remove missing predictions for prognosticators
  filter(!is.na(prediction)) %>%
# count number of each type of prediction by year
  group_by(year, prediction) %>%
  count() %>%
  ungroup() %>%
  filter(year %in% c(1983:1990))

predictions %>%
# remove missing predictions for prognosticators
  filter(!is.na(prediction)) %>%
# count number of each type of prediction by year
  group_by(year, prediction) %>%
  count() %>%
  ungroup() %>%
# keep only years from 1983 to 1990
# read this as filter rows where year is in the set of 1983 to 1990
  filter(year %in% c(1983:1990)) %>%
  complete(year, prediction, fill=list(n = 0)) 
```

