---
title: "DPS COVID-19 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
  library(flexdashboard)
  library(shiny)
  library(shinyWidgets)
  library(tidyverse)

# ** STEP 1 **
# add packages here and runtime: shiny in the YAML to enable Shiny reactivity
```

```{r global, include=FALSE}
# global chunk is important for Shiny
# https://pkgs.rstudio.com/flexdashboard/articles/shiny.html#loading-data

# import and process the DPS COVID data
  source("dps.R")
```

<!-- # ** STEP 2 **

Create at least one static plot that you will make reactive
You will eventually copy/paste this chart to a different chunk in your layout
Leave the next chunk to eval=FALSE so it does not run when knit
-->

```{r static, eval=FALSE}
  
# some helpers you might want to use
# median line
  dps_median <- dps %>%
    filter(level!="Central Services") %>%
    group_by(level, start_date) %>%
    summarize(students = median(students))

# annotate n
  dps_n <- dps %>%
    filter(level!="Central Services") %>%
    distinct(site_name, .keep_all = TRUE) %>%
    count(level) %>%
    mutate(date = lubridate::ymd("2021-08-01")) %>%
    mutate(label = paste0(n, " schools"))

# annotate cases
  dps_cases <- dps %>%
    filter(level!="Central Services") %>%
    group_by(level) %>%
    summarize(total_students = sum(students)) %>%
    mutate(date = lubridate::ymd("2021-08-01")) %>%
    mutate(label = paste0(total_students, " total cases"))

# subtitle date min
  date_min <- dps %>%
    summarize(min = min(start_date)) %>%
    mutate(month = lubridate::month(min, label = TRUE, abbr = FALSE),
           day = lubridate::day(min),
           year = lubridate::year(min),
           date = paste0(month, " ", day, ", ", year)) %>%
    pull(date)

# subtitle date max
  date_max <- dps %>%
    summarize(max = max(start_date)) %>%
    mutate(month = lubridate::month(max, label = TRUE, abbr = FALSE),
           day = lubridate::day(max),
           year = lubridate::year(max),
           date = paste0(month, " ", day, ", ", year)) %>%
    pull(date)
  
# plot
  dps %>%
    filter(level!="Central Services") %>%
    ggplot(aes(x=start_date, y=students)) +
      geom_smooth(color="grey", aes(group=site_name), se = FALSE,
                  alpha = 0.3, size = .4) +
      geom_smooth(data = dps_median, aes(x=start_date, y=students), se = FALSE,
                  alpha = 1, size = 1) +
      geom_jitter(data = dps %>% filter(students > 10),
                  alpha = 0.3, shape = 21) +
      geom_text(data = dps_n, aes(x=date, y = 50, label=label),
                hjust=0) +
      geom_text(data = dps_cases, aes(x=date, y = 43, label=label),
              hjust=0) +
      facet_wrap(~ level, ncol = 1) +
      theme_bw() +
      theme(panel.grid.major.x = element_blank(),
            panel.grid.minor = element_blank(),
            plot.caption = element_text(margin=margin(15,0,0,0)),
            plot.title = element_text(face="bold")) +
      labs(x=NULL, y=NULL,
           title = str_wrap("Fewer than 10% of students at Durham Public Schools have tested positive for COVID-19 during Delta and Omicron waves", 60),
           subtitle = paste0("Weekly reported cases ",
                             "(", date_min, "-", date_max, ")"),
           caption = "~32,000 students attending school on-site. Median cases show in blue.\nData Source: Durham Public Schools, https://tinyurl.com/mr32wdzs\n@ericpgreen")
```


<!-- # ** STEP 3 **

Add a sidebar column below this comment section before STEP 4
https://pkgs.rstudio.com/flexdashboard/articles/shiny.html#input-sidebar
-->


Column {.sidebar}
-----------------------------------------------------------------------

<!-- # ** STEP 4 **

Decide on inputs to make your plot reactive
https://pkgs.rstudio.com/flexdashboard/articles/shiny.html#input-sidebar
-->

```{r inputs}


checkboxGroupButtons(
   inputId = "school_level",
   label = "Level:",
   choices = c("Elementary", "Middle", "High"),
   direction = "vertical",
   selected = c("Elementary", "Middle", "High")
)

awesomeRadio(
   inputId = "students_staff",
   label = "Students or Staff", 
    choices = c("students", "staff"),
   selected = "students",
   status = "primary"
)
```

<!-- # ** STEP 5 **

Decide on the remaining layout for your dashboard
https://pkgs.rstudio.com/flexdashboard/articles/using.html#layout
-->

Column
-----------------------------------------------------------------------

### Cases

<!-- # ** STEP 6 **

Move the code chunk below to the appropriate place in your layout
Paste your static plot code inside renderPlot({ })
Connect your plot to the inputs you created in Step 4 with input$id
Set to eval=TRUE or remove eval
-->

```{r reactiveplot}
  renderPlot({
    
  # filtered data
    dps_shiny <- dps %>%
      pivot_longer(cols = c(students, staff), 
                   names_to = "who", 
                   values_to = "cases") %>%
      filter(level!="Central Services") %>%
      filter(level %in% input$school_level) %>%
      filter(who %in% input$students_staff)
      
  # median line
    dps_median <- dps_shiny %>%
      filter(level!="Central Services") %>%
      group_by(level, start_date) %>%
      summarize(cases = median(cases))
  
  # annotate n
    dps_n <- dps_shiny %>%
      filter(level!="Central Services") %>%
      distinct(site_name, .keep_all = TRUE) %>%
      count(level) %>%
      mutate(date = lubridate::ymd("2021-08-01")) %>%
      mutate(label = paste0(n, " schools"))
  
  # annotate cases
    dps_cases <- dps_shiny %>%
      filter(level!="Central Services") %>%
      group_by(level) %>%
      summarize(total_cases = sum(cases)) %>%
      mutate(date = lubridate::ymd("2021-08-01")) %>%
      mutate(label = paste0(total_cases, " total cases"))
  
  # subtitle date min
    date_min <- dps_shiny %>%
      summarize(min = min(start_date)) %>%
      mutate(month = lubridate::month(min, label = TRUE, abbr = FALSE),
             day = lubridate::day(min),
             year = lubridate::year(min),
             date = paste0(month, " ", day, ", ", year)) %>%
      pull(date)
  
  # subtitle date max
    date_max <- dps_shiny %>%
      summarize(max = max(start_date)) %>%
      mutate(month = lubridate::month(max, label = TRUE, abbr = FALSE),
             day = lubridate::day(max),
             year = lubridate::year(max),
             date = paste0(month, " ", day, ", ", year)) %>%
      pull(date)
    
  # plot
   dps_shiny %>%
    ggplot(aes(x=start_date, y=cases)) +
      geom_smooth(color="grey", aes(group=site_name), se = FALSE,
                  alpha = 0.3, size = .4) +
      geom_smooth(data = dps_median, aes(x=start_date, y=cases), se = FALSE,
                  alpha = 1, size = 1) +
      geom_jitter(data = dps_shiny %>% filter(cases > 10),
                  alpha = 0.3, shape = 21) +
      geom_text(data = dps_n, aes(x=date, y = max(dps_shiny$cases), label=label),
                hjust=0) +
      geom_text(data = dps_cases, aes(x=date, y = max(dps_shiny$cases)-(max(dps_shiny$cases)*.2),
                                      label=label),
              hjust=0) +
      facet_wrap(~ level, ncol = 1) +
      theme_bw() +
      theme(panel.grid.major.x = element_blank(),
            panel.grid.minor = element_blank(),
            plot.caption = element_text(margin=margin(15,0,0,0)),
            plot.title = element_text(face="bold")) +
      labs(x=NULL, y=NULL,
           title = str_wrap(paste0("Weekly reported cases: ", input$students_staff), 60),
           subtitle = paste0(date_min, "-", date_max),
           caption = "Median cases show in blue.\nData Source: Durham Public Schools, https://tinyurl.com/mr32wdzs\n@ericpgreen")
    
  })
```




<!-- # ** STEP 7 **

Time permitting, change the theme
https://pkgs.rstudio.com/flexdashboard/articles/theme.html#bootswatch-themes

Run:
install.packages("bslib")

Pick from options here:
https://bootswatch.com/

Edit your YAML with the name of the theme you would like:

---
output:
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty
---


Alternatively, create a custom theme:
https://pkgs.rstudio.com/flexdashboard/articles/theme.html#custom-themes

Run: 
install.packages("bslib")
install.packages("sass")

Edit your YAML with custom colors and Google Fonts:

---
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      navbar-bg: "#3ADAC6"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
---

-->



